version: '3.8'
services:
  client:
    build: 
      context: .
      dockerfile: .docker/dev.dockerfile
    ports:
      - "4200:4200"
    command: ng serve --host=0.0.0.0 --port 4200
    volumes:
      - .:/app

  api:
    ports:
      - "3000:3000"